# sudo ./install -p dotbot-apt/apt.py --p dotbot-snap/snap.py -c packages.config.yaml

- apt:
    - audacity
    - build-essential
    - curl
    - libbz2-dev
    - libncursesw5-dev
    - libffi-dev
    - liblzma-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libxmlsec1-dev
    - libxml2-dev
    - llvm
    - make
    - pass
    - pass-git-helper
    - python-is-python3
    - snapd
    - tk-dev
    - wget
    - xz-utils
    - zlib1g-dev
    - zsh

- snap:
    - dbeaver-ce
    - telegram-desktop
    - whatsdesk
