# From https://github.com/anishathalye/dotfiles/blob/master/.github/workflows/build.yml

name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *" # Schedule monthly

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run: |
          mkdir -p ~/dotfiles-install-dir
      - run: |
          HOME=~/dotfiles-install-dir sudo ./install -p dotbot-apt/apt.py -p dotbot-snap/snap.py -c packages.config.yaml
      - run: |
          HOME=~/dotfiles-install-dir ./install --plugin-dir ./dotbot-vscode