# From https://github.com/anishathalye/dotfiles/blob/master/.github/workflows/build.yml

name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *" # Schedule monthly

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - run: |
          mkdir -p ~/dotfiles-install-dir
      
      - name: Install elevated permissions dotfiles
        run: |
          HOME=~/dotfiles-install-dir sudo ./install -p dotbot-apt/apt.py -p dotbot-snap/snap.py -c elevated-permissions.config.yaml
      
      - name: Install default permissions dotfiles
        run: |
          HOME=~/dotfiles-install-dir ./install -p dotbot-vscode/vscode.py
